import { MEDIA_AUDIO_FIELD_LABELS } from "./media-audio-field-metadata.js";
import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  meta: "元数据",
  "meta.lastTouchedVersion": "配置最后修改版本",
  "meta.lastTouchedAt": "配置最后修改时间",
  env: "环境",
  "env.shellEnv": "Shell 环境导入",
  "env.shellEnv.enabled": "启用 Shell 环境导入",
  "env.shellEnv.timeoutMs": "Shell 环境导入超时（毫秒）",
  "env.vars": "环境变量覆盖",
  wizard: "安装向导状态",
  "wizard.lastRunAt": "向导上次运行时间戳",
  "wizard.lastRunVersion": "向导上次运行版本",
  "wizard.lastRunCommit": "向导上次运行提交",
  "wizard.lastRunCommand": "向导上次运行命令",
  "wizard.lastRunMode": "向导上次运行模式",
  diagnostics: "诊断",
  "diagnostics.otel": "OpenTelemetry",
  "diagnostics.cacheTrace": "缓存追踪",
  logging: "日志",
  "logging.level": "日志级别",
  "logging.file": "日志文件路径",
  "logging.consoleLevel": "控制台日志级别",
  "logging.consoleStyle": "控制台日志样式",
  "logging.redactSensitive": "敏感数据脱敏模式",
  "logging.redactPatterns": "自定义脱敏规则",
  cli: "CLI",
  "cli.banner": "CLI 横幅",
  "cli.banner.taglineMode": "CLI 横幅标语模式",
  update: "更新",
  "update.channel": "更新通道",
  "update.checkOnStart": "启动时检查更新",
  "update.auto.enabled": "启用自动更新",
  "update.auto.stableDelayHours": "自动更新稳定版延迟（小时）",
  "update.auto.stableJitterHours": "自动更新稳定版抖动（小时）",
  "update.auto.betaCheckIntervalHours": "自动更新 Beta 检查间隔（小时）",
  "diagnostics.enabled": "启用诊断",
  "diagnostics.flags": "诊断标志",
  "diagnostics.stuckSessionWarnMs": "卡顿会话警告阈值（毫秒）",
  "diagnostics.otel.enabled": "启用 OpenTelemetry",
  "diagnostics.otel.endpoint": "OpenTelemetry 端点",
  "diagnostics.otel.protocol": "OpenTelemetry 协议",
  "diagnostics.otel.headers": "OpenTelemetry 请求头",
  "diagnostics.otel.serviceName": "OpenTelemetry 服务名称",
  "diagnostics.otel.traces": "启用 OpenTelemetry 追踪",
  "diagnostics.otel.metrics": "启用 OpenTelemetry 指标",
  "diagnostics.otel.logs": "启用 OpenTelemetry 日志",
  "diagnostics.otel.sampleRate": "OpenTelemetry 追踪采样率",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry 刷新间隔（毫秒）",
  "diagnostics.cacheTrace.enabled": "启用缓存追踪",
  "diagnostics.cacheTrace.filePath": "缓存追踪文件路径",
  "diagnostics.cacheTrace.includeMessages": "缓存追踪包含消息",
  "diagnostics.cacheTrace.includePrompt": "缓存追踪包含提示词",
  "diagnostics.cacheTrace.includeSystem": "缓存追踪包含系统消息",
  "agents.list.*.identity.avatar": "身份头像",
  "agents.list.*.skills": "代理技能筛选",
  "agents.list[].runtime": "代理运行时",
  "agents.list[].runtime.type": "代理运行时类型",
  "agents.list[].runtime.acp": "代理 ACP 运行时",
  "agents.list[].runtime.acp.agent": "代理 ACP 编排代理",
  "agents.list[].runtime.acp.backend": "代理 ACP 后端",
  "agents.list[].runtime.acp.mode": "代理 ACP 模式",
  "agents.list[].runtime.acp.cwd": "代理 ACP 工作目录",
  agents: "代理",
  "agents.defaults": "代理默认值",
  "agents.list": "代理列表",
  gateway: "网关",
  "gateway.port": "网关端口",
  "gateway.mode": "网关模式",
  "gateway.bind": "网关绑定模式",
  "gateway.customBindHost": "网关自定义绑定主机",
  "gateway.controlUi": "控制面板",
  "gateway.controlUi.enabled": "启用控制面板",
  "gateway.auth": "网关认证",
  "gateway.auth.mode": "网关认证模式",
  "gateway.auth.allowTailscale": "网关认证允许 Tailscale 身份",
  "gateway.auth.rateLimit": "网关认证速率限制",
  "gateway.auth.trustedProxy": "网关可信代理认证",
  "gateway.trustedProxies": "网关可信代理 CIDR",
  "gateway.allowRealIpFallback": "网关允许 x-real-ip 回退",
  "gateway.tools": "网关工具暴露策略",
  "gateway.tools.allow": "网关工具允许列表",
  "gateway.tools.deny": "网关工具拒绝列表",
  "gateway.channelHealthCheckMinutes": "网关通道健康检查间隔（分钟）",
  "gateway.tailscale": "网关 Tailscale",
  "gateway.tailscale.mode": "网关 Tailscale 模式",
  "gateway.tailscale.resetOnExit": "网关 Tailscale 退出时重置",
  "gateway.remote": "远程网关",
  "gateway.remote.transport": "远程网关传输方式",
  "gateway.reload": "配置重载",
  "gateway.tls": "网关 TLS",
  "gateway.tls.enabled": "启用网关 TLS",
  "gateway.tls.autoGenerate": "网关 TLS 自动生成证书",
  "gateway.tls.certPath": "网关 TLS 证书路径",
  "gateway.tls.keyPath": "网关 TLS 密钥路径",
  "gateway.tls.caPath": "网关 TLS CA 路径",
  "gateway.http": "网关 HTTP API",
  "gateway.http.endpoints": "网关 HTTP 端点",
  "gateway.http.securityHeaders": "网关 HTTP 安全头",
  "gateway.http.securityHeaders.strictTransportSecurity": "严格传输安全头",
  "gateway.remote.url": "远程网关 URL",
  "gateway.remote.sshTarget": "远程网关 SSH 目标",
  "gateway.remote.sshIdentity": "远程网关 SSH 身份",
  "gateway.remote.token": "远程网关令牌",
  "gateway.remote.password": "远程网关密码",
  "gateway.remote.tlsFingerprint": "远程网关 TLS 指纹",
  "gateway.auth.token": "网关令牌",
  "gateway.auth.password": "网关密码",
  browser: "浏览器",
  "browser.enabled": "启用浏览器",
  "browser.cdpUrl": "浏览器 CDP URL",
  "browser.color": "浏览器主题色",
  "browser.executablePath": "浏览器可执行文件路径",
  "browser.headless": "浏览器无头模式",
  "browser.noSandbox": "浏览器无沙箱模式",
  "browser.attachOnly": "浏览器仅附加模式",
  "browser.cdpPortRangeStart": "浏览器 CDP 端口范围起始",
  "browser.defaultProfile": "浏览器默认配置",
  "browser.relayBindHost": "浏览器中继绑定地址",
  "browser.profiles": "浏览器配置列表",
  "browser.profiles.*.cdpPort": "浏览器配置 CDP 端口",
  "browser.profiles.*.cdpUrl": "浏览器配置 CDP URL",
  "browser.profiles.*.driver": "浏览器配置驱动",
  "browser.profiles.*.attachOnly": "浏览器配置仅附加模式",
  "browser.profiles.*.color": "浏览器配置主题色",
  tools: "工具",
  "tools.allow": "工具允许列表",
  "tools.deny": "工具拒绝列表",
  "tools.web": "网页工具",
  "tools.exec": "执行工具",
  "tools.media.image.enabled": "启用图像理解",
  "tools.media.image.maxBytes": "图像理解最大字节数",
  "tools.media.image.maxChars": "图像理解最大字符数",
  "tools.media.image.prompt": "图像理解提示词",
  "tools.media.image.timeoutSeconds": "图像理解超时（秒）",
  "tools.media.image.attachments": "图像理解附件策略",
  "tools.media.image.models": "图像理解模型",
  "tools.media.image.scope": "图像理解范围",
  "tools.media.models": "媒体理解共享模型",
  "tools.media.concurrency": "媒体理解并发数",
  ...MEDIA_AUDIO_FIELD_LABELS,
  "tools.media.video.enabled": "启用视频理解",
  "tools.media.video.maxBytes": "视频理解最大字节数",
  "tools.media.video.maxChars": "视频理解最大字符数",
  "tools.media.video.prompt": "视频理解提示词",
  "tools.media.video.timeoutSeconds": "视频理解超时（秒）",
  "tools.media.video.attachments": "视频理解附件策略",
  "tools.media.video.models": "视频理解模型",
  "tools.media.video.scope": "视频理解范围",
  "tools.links.enabled": "启用链接理解",
  "tools.links.maxLinks": "链接理解最大链接数",
  "tools.links.timeoutSeconds": "链接理解超时（秒）",
  "tools.links.models": "链接理解模型",
  "tools.links.scope": "链接理解范围",
  "tools.profile": "工具配置",
  "tools.alsoAllow": "工具允许列表附加",
  "agents.list[].tools.profile": "代理工具配置",
  "agents.list[].tools.alsoAllow": "代理工具允许列表附加",
  "tools.byProvider": "按提供者分工具策略",
  "agents.list[].tools.byProvider": "代理按提供者分工具策略",
  "tools.exec.applyPatch.enabled": "启用 apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch 仅工作区",
  "tools.exec.applyPatch.allowModels": "apply_patch 模型允许列表",
  "tools.loopDetection.enabled": "工具循环检测",
  "tools.loopDetection.historySize": "工具循环历史大小",
  "tools.loopDetection.warningThreshold": "工具循环警告阈值",
  "tools.loopDetection.criticalThreshold": "工具循环严重阈值",
  "tools.loopDetection.globalCircuitBreakerThreshold": "工具循环全局熔断阈值",
  "tools.loopDetection.detectors.genericRepeat": "工具循环通用重复检测",
  "tools.loopDetection.detectors.knownPollNoProgress": "工具循环轮询无进展检测",
  "tools.loopDetection.detectors.pingPong": "工具循环乒乓检测",
  "tools.fs.workspaceOnly": "仅工作区文件系统工具",
  "tools.sessions.visibility": "会话工具可见性",
  "tools.exec.notifyOnExit": "执行退出通知",
  "tools.exec.notifyOnExitEmptySuccess": "执行空结果成功通知",
  "tools.exec.approvalRunningNoticeMs": "执行审批运行通知（毫秒）",
  "tools.exec.host": "执行主机",
  "tools.exec.security": "执行安全",
  "tools.exec.ask": "执行询问",
  "tools.exec.node": "执行节点绑定",
  "tools.agentToAgent": "代理间工具访问",
  "tools.agentToAgent.enabled": "启用代理间工具",
  "tools.agentToAgent.allow": "代理间目标允许列表",
  "tools.elevated": "提升工具访问",
  "tools.elevated.enabled": "启用提升工具访问",
  "tools.elevated.allowFrom": "提升工具允许规则",
  "tools.subagents": "子代理工具策略",
  "tools.subagents.tools": "子代理工具允许/拒绝策略",
  "tools.sandbox": "沙箱工具策略",
  "tools.sandbox.tools": "沙箱工具允许/拒绝策略",
  "tools.exec.pathPrepend": "执行 PATH 前缀",
  "tools.exec.safeBins": "执行安全二进制",
  "tools.exec.safeBinTrustedDirs": "执行安全二进制可信目录",
  "tools.exec.safeBinProfiles": "执行安全二进制配置",
  approvals: "审批",
  "approvals.exec": "执行审批转发",
  "approvals.exec.enabled": "转发执行审批",
  "approvals.exec.mode": "审批转发模式",
  "approvals.exec.agentFilter": "审批代理筛选",
  "approvals.exec.sessionFilter": "审批会话筛选",
  "approvals.exec.targets": "审批转发目标",
  "approvals.exec.targets[].channel": "审批目标通道",
  "approvals.exec.targets[].to": "审批目标地址",
  "approvals.exec.targets[].accountId": "审批目标账户 ID",
  "approvals.exec.targets[].threadId": "审批目标线程 ID",
  "tools.message.allowCrossContextSend": "允许跨上下文消息",
  "tools.message.crossContext.allowWithinProvider": "允许跨上下文（同提供者）",
  "tools.message.crossContext.allowAcrossProviders": "允许跨上下文（跨提供者）",
  "tools.message.crossContext.marker.enabled": "跨上下文标记",
  "tools.message.crossContext.marker.prefix": "跨上下文标记前缀",
  "tools.message.crossContext.marker.suffix": "跨上下文标记后缀",
  "tools.message.broadcast.enabled": "启用消息广播",
  "tools.web.search.enabled": "启用网页搜索工具",
  "tools.web.search.provider": "网页搜索提供者",
  "tools.web.search.apiKey": "Brave 搜索 API 密钥",
  "tools.web.search.maxResults": "网页搜索最大结果数",
  "tools.web.search.timeoutSeconds": "网页搜索超时（秒）",
  "tools.web.search.cacheTtlMinutes": "网页搜索缓存有效期（分钟）",
  "tools.web.search.brave.mode": "Brave 搜索模式",
  "tools.web.search.gemini.apiKey": "Gemini 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.gemini.model": "Gemini 搜索模型",
  "tools.web.search.grok.apiKey": "Grok 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.grok.model": "Grok 搜索模型",
  "tools.web.search.kimi.apiKey": "Kimi 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.kimi.baseUrl": "Kimi 搜索基础 URL",
  "tools.web.search.kimi.model": "Kimi 搜索模型",
  "tools.web.search.perplexity.apiKey": "Perplexity API 密钥", // pragma: allowlist secret
  "tools.web.search.perplexity.baseUrl": "Perplexity 基础 URL",
  "tools.web.search.perplexity.model": "Perplexity 模型",
  "tools.web.fetch.enabled": "启用网页获取工具",
  "tools.web.fetch.maxChars": "网页获取最大字符数",
  "tools.web.fetch.maxCharsCap": "网页获取硬性最大字符数",
  "tools.web.fetch.timeoutSeconds": "网页获取超时（秒）",
  "tools.web.fetch.cacheTtlMinutes": "网页获取缓存有效期（分钟）",
  "tools.web.fetch.maxRedirects": "网页获取最大重定向次数",
  "tools.web.fetch.userAgent": "网页获取 User-Agent",
  "tools.web.fetch.readability": "网页获取可读性提取",
  "tools.web.fetch.firecrawl.enabled": "启用 Firecrawl 回退",
  "tools.web.fetch.firecrawl.apiKey": "Firecrawl API 密钥", // pragma: allowlist secret
  "tools.web.fetch.firecrawl.baseUrl": "Firecrawl 基础 URL",
  "tools.web.fetch.firecrawl.onlyMainContent": "Firecrawl 仅主要内容",
  "tools.web.fetch.firecrawl.maxAgeMs": "Firecrawl 缓存最大有效期（毫秒）",
  "tools.web.fetch.firecrawl.timeoutSeconds": "Firecrawl 超时（秒）",
  "gateway.controlUi.basePath": "控制面板基础路径",
  "gateway.controlUi.root": "控制面板资源根目录",
  "gateway.controlUi.allowedOrigins": "控制面板允许的来源",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback":
    "危险地允许 Host-Header 来源回退",
  "gateway.controlUi.allowInsecureAuth": "控制面板不安全认证开关",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "危险地禁用控制面板设备认证",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI 聊天补全端点",
  "gateway.http.endpoints.chatCompletions.maxBodyBytes": "OpenAI 聊天补全最大请求体字节数",
  "gateway.http.endpoints.chatCompletions.maxImageParts": "OpenAI 聊天补全最大图片分块数",
  "gateway.http.endpoints.chatCompletions.maxTotalImageBytes":
    "OpenAI 聊天补全最大图片总字节数",
  "gateway.http.endpoints.chatCompletions.images": "OpenAI 聊天补全图片限制",
  "gateway.http.endpoints.chatCompletions.images.allowUrl":
    "OpenAI 聊天补全允许图片 URL",
  "gateway.http.endpoints.chatCompletions.images.urlAllowlist":
    "OpenAI 聊天补全图片 URL 允许列表",
  "gateway.http.endpoints.chatCompletions.images.allowedMimes":
    "OpenAI 聊天补全图片 MIME 允许列表",
  "gateway.http.endpoints.chatCompletions.images.maxBytes":
    "OpenAI 聊天补全图片最大字节数",
  "gateway.http.endpoints.chatCompletions.images.maxRedirects":
    "OpenAI 聊天补全图片最大重定向次数",
  "gateway.http.endpoints.chatCompletions.images.timeoutMs":
    "OpenAI 聊天补全图片超时（毫秒）",
  "gateway.reload.mode": "配置重载模式",
  "gateway.reload.debounceMs": "配置重载防抖（毫秒）",
  "gateway.nodes.browser.mode": "网关节点浏览器模式",
  "gateway.nodes.browser.node": "网关节点浏览器固定",
  "gateway.nodes.allowCommands": "网关节点允许列表（额外命令）",
  "gateway.nodes.denyCommands": "网关节点拒绝列表",
  nodeHost: "节点主机",
  "nodeHost.browserProxy": "节点浏览器代理",
  "nodeHost.browserProxy.enabled": "启用节点浏览器代理",
  "nodeHost.browserProxy.allowProfiles": "节点浏览器代理允许的配置",
  media: "媒体",
  "media.preserveFilenames": "保留媒体文件名",
  "media.ttlHours": "媒体保留有效期（小时）",
  audio: "音频",
  "audio.transcription": "音频转录",
  "audio.transcription.command": "音频转录命令",
  "audio.transcription.timeoutSeconds": "音频转录超时（秒）",
  bindings: "绑定",
  "bindings[].type": "绑定类型",
  "bindings[].agentId": "绑定代理 ID",
  "bindings[].match": "绑定匹配规则",
  "bindings[].match.channel": "绑定通道",
  "bindings[].match.accountId": "绑定账户 ID",
  "bindings[].match.peer": "绑定对等方匹配",
  "bindings[].match.peer.kind": "绑定对等方类型",
  "bindings[].match.peer.id": "绑定对等方 ID",
  "bindings[].match.guildId": "绑定服务器 ID",
  "bindings[].match.teamId": "绑定团队 ID",
  "bindings[].match.roles": "绑定角色",
  "bindings[].acp": "ACP 绑定覆盖",
  "bindings[].acp.mode": "ACP 绑定模式",
  "bindings[].acp.label": "ACP 绑定标签",
  "bindings[].acp.cwd": "ACP 绑定工作目录",
  "bindings[].acp.backend": "ACP 绑定后端",
  broadcast: "广播",
  "broadcast.strategy": "广播策略",
  "broadcast.*": "广播目标列表",
  "skills.load.watch": "监听技能",
  "skills.load.watchDebounceMs": "技能监听防抖（毫秒）",
  "agents.defaults.workspace": "工作区",
  "agents.defaults.repoRoot": "仓库根目录",
  "agents.defaults.bootstrapMaxChars": "引导最大字符数",
  "agents.defaults.bootstrapTotalMaxChars": "引导总最大字符数",
  "agents.defaults.bootstrapPromptTruncationWarning": "引导提示词截断警告",
  "agents.defaults.envelopeTimezone": "信封时区",
  "agents.defaults.envelopeTimestamp": "信封时间戳",
  "agents.defaults.envelopeElapsed": "信封已用时间",
  "agents.defaults.memorySearch": "记忆搜索",
  "agents.defaults.memorySearch.enabled": "启用记忆搜索",
  "agents.defaults.memorySearch.sources": "记忆搜索来源",
  "agents.defaults.memorySearch.extraPaths": "额外记忆路径",
  "agents.defaults.memorySearch.multimodal": "记忆搜索多模态",
  "agents.defaults.memorySearch.multimodal.enabled": "启用记忆搜索多模态",
  "agents.defaults.memorySearch.multimodal.modalities": "记忆搜索多模态模式",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "记忆搜索多模态最大文件字节数",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "记忆搜索会话索引（实验性）",
  "agents.defaults.memorySearch.provider": "记忆搜索提供者",
  "agents.defaults.memorySearch.remote.baseUrl": "远程嵌入基础 URL",
  "agents.defaults.memorySearch.remote.apiKey": "远程嵌入 API 密钥",
  "agents.defaults.memorySearch.remote.headers": "远程嵌入请求头",
  "agents.defaults.memorySearch.remote.batch.enabled": "启用远程批量嵌入",
  "agents.defaults.memorySearch.remote.batch.wait": "远程批量等待完成",
  "agents.defaults.memorySearch.remote.batch.concurrency": "远程批量并发数",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "远程批量轮询间隔（毫秒）",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "远程批量超时（分钟）",
  "agents.defaults.memorySearch.model": "记忆搜索模型",
  "agents.defaults.memorySearch.outputDimensionality": "记忆搜索输出维度",
  "agents.defaults.memorySearch.fallback": "记忆搜索回退",
  "agents.defaults.memorySearch.local.modelPath": "本地嵌入模型路径",
  "agents.defaults.memorySearch.store.path": "记忆搜索索引路径",
  "agents.defaults.memorySearch.store.vector.enabled": "记忆搜索向量索引",
  "agents.defaults.memorySearch.store.vector.extensionPath": "记忆搜索向量扩展路径",
  "agents.defaults.memorySearch.chunking.tokens": "记忆分块令牌数",
  "agents.defaults.memorySearch.chunking.overlap": "记忆分块重叠令牌数",
  "agents.defaults.memorySearch.sync.onSessionStart": "会话开始时索引",
  "agents.defaults.memorySearch.sync.onSearch": "搜索时索引（懒加载）",
  "agents.defaults.memorySearch.sync.watch": "监听记忆文件",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "记忆监听防抖（毫秒）",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "会话增量字节数",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "会话增量消息数",
  "agents.defaults.memorySearch.query.maxResults": "记忆搜索最大结果数",
  "agents.defaults.memorySearch.query.minScore": "记忆搜索最低分数",
  "agents.defaults.memorySearch.query.hybrid.enabled": "记忆搜索混合模式",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "记忆搜索向量权重",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "记忆搜索文本权重",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "记忆搜索混合候选倍数",
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "记忆搜索 MMR 重排序",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "记忆搜索 MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "记忆搜索时间衰减",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "记忆搜索时间衰减半衰期（天）",
  "agents.defaults.memorySearch.cache.enabled": "记忆搜索嵌入缓存",
  "agents.defaults.memorySearch.cache.maxEntries": "记忆搜索嵌入缓存最大条目数",
  memory: "记忆",
  "memory.backend": "记忆后端",
  "memory.citations": "记忆引用模式",
  "memory.qmd.command": "QMD 二进制",
  "memory.qmd.mcporter": "QMD MCPorter",
  "memory.qmd.mcporter.enabled": "启用 QMD MCPorter",
  "memory.qmd.mcporter.serverName": "QMD MCPorter 服务器名称",
  "memory.qmd.mcporter.startDaemon": "QMD MCPorter 启动守护进程",
  "memory.qmd.searchMode": "QMD 搜索模式",
  "memory.qmd.includeDefaultMemory": "QMD 包含默认记忆",
  "memory.qmd.paths": "QMD 额外路径",
  "memory.qmd.paths.path": "QMD 路径",
  "memory.qmd.paths.pattern": "QMD 路径模式",
  "memory.qmd.paths.name": "QMD 路径名称",
  "memory.qmd.sessions.enabled": "QMD 会话索引",
  "memory.qmd.sessions.exportDir": "QMD 会话导出目录",
  "memory.qmd.sessions.retentionDays": "QMD 会话保留（天）",
  "memory.qmd.update.interval": "QMD 更新间隔",
  "memory.qmd.update.debounceMs": "QMD 更新防抖（毫秒）",
  "memory.qmd.update.onBoot": "启动时 QMD 更新",
  "memory.qmd.update.waitForBootSync": "QMD 等待启动同步",
  "memory.qmd.update.embedInterval": "QMD 嵌入间隔",
  "memory.qmd.update.commandTimeoutMs": "QMD 命令超时（毫秒）",
  "memory.qmd.update.updateTimeoutMs": "QMD 更新超时（毫秒）",
  "memory.qmd.update.embedTimeoutMs": "QMD 嵌入超时（毫秒）",
  "memory.qmd.limits.maxResults": "QMD 最大结果数",
  "memory.qmd.limits.maxSnippetChars": "QMD 最大片段字符数",
  "memory.qmd.limits.maxInjectedChars": "QMD 最大注入字符数",
  "memory.qmd.limits.timeoutMs": "QMD 搜索超时（毫秒）",
  "memory.qmd.scope": "QMD 展示范围",
  auth: "认证",
  "auth.profiles": "认证配置",
  "auth.order": "认证配置顺序",
  "auth.cooldowns": "认证冷却",
  acp: "ACP",
  "acp.enabled": "启用 ACP",
  "acp.dispatch.enabled": "启用 ACP 调度",
  "acp.backend": "ACP 后端",
  "acp.defaultAgent": "ACP 默认代理",
  "acp.allowedAgents": "ACP 允许的代理",
  "acp.maxConcurrentSessions": "ACP 最大并发会话",
  "acp.stream": "ACP 流",
  "acp.stream.coalesceIdleMs": "ACP 流空闲合并（毫秒）",
  "acp.stream.maxChunkChars": "ACP 流最大分块字符数",
  "acp.stream.repeatSuppression": "ACP 流重复抑制",
  "acp.stream.deliveryMode": "ACP 流传输模式",
  "acp.stream.hiddenBoundarySeparator": "ACP 流隐藏边界分隔符",
  "acp.stream.maxOutputChars": "ACP 流最大输出字符数",
  "acp.stream.maxSessionUpdateChars": "ACP 流最大会话更新字符数",
  "acp.stream.tagVisibility": "ACP 流标签可见性",
  "acp.runtime.ttlMinutes": "ACP 运行时存活时间（分钟）",
  "acp.runtime.installCommand": "ACP 运行时安装命令",
  models: "模型",
  "models.mode": "模型目录模式",
  "models.providers": "模型提供者",
  "models.providers.*.baseUrl": "模型提供者基础 URL",
  "models.providers.*.apiKey": "模型提供者 API 密钥", // pragma: allowlist secret
  "models.providers.*.auth": "模型提供者认证模式",
  "models.providers.*.api": "模型提供者 API 适配器",
  "models.providers.*.injectNumCtxForOpenAICompat": "模型提供者注入 num_ctx（OpenAI 兼容）",
  "models.providers.*.headers": "模型提供者请求头",
  "models.providers.*.authHeader": "模型提供者授权头",
  "models.providers.*.models": "模型提供者模型列表",
  "models.bedrockDiscovery": "Bedrock 模型发现",
  "models.bedrockDiscovery.enabled": "启用 Bedrock 发现",
  "models.bedrockDiscovery.region": "Bedrock 发现区域",
  "models.bedrockDiscovery.providerFilter": "Bedrock 发现提供者筛选",
  "models.bedrockDiscovery.refreshInterval": "Bedrock 发现刷新间隔（秒）",
  "models.bedrockDiscovery.defaultContextWindow": "Bedrock 默认上下文窗口",
  "models.bedrockDiscovery.defaultMaxTokens": "Bedrock 默认最大令牌数",
  "auth.cooldowns.billingBackoffHours": "计费退避（小时）",
  "auth.cooldowns.billingBackoffHoursByProvider": "计费退避覆盖",
  "auth.cooldowns.billingMaxHours": "计费退避上限（小时）",
  "auth.cooldowns.failureWindowHours": "故障转移窗口（小时）",
  "agents.defaults.models": "模型",
  "agents.defaults.model.primary": "主模型",
  "agents.defaults.model.fallbacks": "模型回退",
  "agents.defaults.imageModel.primary": "图像模型",
  "agents.defaults.imageModel.fallbacks": "图像模型回退",
  "agents.defaults.pdfModel.primary": "PDF 模型",
  "agents.defaults.pdfModel.fallbacks": "PDF 模型回退",
  "agents.defaults.pdfMaxBytesMb": "PDF 最大大小（MB）",
  "agents.defaults.pdfMaxPages": "PDF 最大页数",
  "agents.defaults.imageMaxDimensionPx": "图像最大尺寸（像素）",
  "agents.defaults.humanDelay.mode": "拟人延迟模式",
  "agents.defaults.humanDelay.minMs": "拟人延迟最小值（毫秒）",
  "agents.defaults.humanDelay.maxMs": "拟人延迟最大值（毫秒）",
  "agents.defaults.cliBackends": "CLI 后端",
  "agents.defaults.compaction": "压缩",
  "agents.defaults.compaction.mode": "压缩模式",
  "agents.defaults.compaction.reserveTokens": "压缩保留令牌数",
  "agents.defaults.compaction.keepRecentTokens": "压缩保留最近令牌数",
  "agents.defaults.compaction.reserveTokensFloor": "压缩保留令牌下限",
  "agents.defaults.compaction.maxHistoryShare": "压缩最大历史占比",
  "agents.defaults.compaction.identifierPolicy": "压缩标识符策略",
  "agents.defaults.compaction.identifierInstructions": "压缩标识符指令",
  "agents.defaults.compaction.recentTurnsPreserve": "压缩保留最近轮次",
  "agents.defaults.compaction.qualityGuard": "压缩质量保护",
  "agents.defaults.compaction.qualityGuard.enabled": "启用压缩质量保护",
  "agents.defaults.compaction.qualityGuard.maxRetries": "压缩质量保护最大重试次数",
  "agents.defaults.compaction.postCompactionSections": "压缩后上下文段落",
  "agents.defaults.compaction.model": "压缩模型覆盖",
  "agents.defaults.compaction.memoryFlush": "压缩记忆刷新",
  "agents.defaults.compaction.memoryFlush.enabled": "启用压缩记忆刷新",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "压缩记忆刷新软阈值",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "压缩记忆刷新转录大小阈值",
  "agents.defaults.compaction.memoryFlush.prompt": "压缩记忆刷新提示词",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "压缩记忆刷新系统提示词",
  "agents.defaults.embeddedPi": "嵌入式 Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "嵌入式 Pi 项目设置策略",
  "agents.defaults.heartbeat.directPolicy": "心跳直接策略",
  "agents.list.*.heartbeat.directPolicy": "心跳直接策略",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "心跳抑制工具错误警告",
  "agents.defaults.sandbox.browser.network": "沙箱浏览器网络",
  "agents.defaults.sandbox.browser.cdpSourceRange": "沙箱浏览器 CDP 源端口范围",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "沙箱 Docker 允许容器命名空间加入",
  commands: "命令",
  "commands.native": "原生命令",
  "commands.nativeSkills": "原生技能命令",
  "commands.text": "文本命令",
  "commands.bash": "允许 Bash 聊天命令",
  "commands.bashForegroundMs": "Bash 前台窗口（毫秒）",
  "commands.config": "允许 /config",
  "commands.debug": "允许 /debug",
  "commands.restart": "允许重启",
  "commands.useAccessGroups": "使用访问组",
  "commands.ownerAllowFrom": "命令所有者",
  "commands.ownerDisplay": "所有者 ID 显示",
  "commands.ownerDisplaySecret": "所有者 ID 哈希密钥", // pragma: allowlist secret
  "commands.allowFrom": "命令提升访问规则",
  ui: "UI",
  "ui.seamColor": "主题色",
  "ui.assistant": "助手外观",
  "ui.assistant.name": "助手名称",
  "ui.assistant.avatar": "助手头像",
  "browser.evaluateEnabled": "启用浏览器执行",
  "browser.snapshotDefaults": "浏览器快照默认值",
  "browser.snapshotDefaults.mode": "浏览器快照模式",
  "browser.ssrfPolicy": "浏览器 SSRF 策略",
  "browser.ssrfPolicy.allowPrivateNetwork": "浏览器允许专用网络",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "浏览器危险地允许专用网络",
  "browser.ssrfPolicy.allowedHostnames": "浏览器允许的主机名",
  "browser.ssrfPolicy.hostnameAllowlist": "浏览器主机名允许列表",
  "browser.remoteCdpTimeoutMs": "远程 CDP 超时（毫秒）",
  "browser.remoteCdpHandshakeTimeoutMs": "远程 CDP 握手超时（毫秒）",
  session: "会话",
  "session.scope": "会话范围",
  "session.dmScope": "私信会话范围",
  "session.identityLinks": "会话身份链接",
  "session.resetTriggers": "会话重置触发器",
  "session.idleMinutes": "会话空闲分钟",
  "session.reset": "会话重置策略",
  "session.reset.mode": "会话重置模式",
  "session.reset.atHour": "会话每日重置时间",
  "session.reset.idleMinutes": "会话重置空闲分钟",
  "session.resetByType": "按聊天类型重置会话",
  "session.resetByType.direct": "会话重置（直接）",
  "session.resetByType.dm": "会话重置（私信已弃用别名）",
  "session.resetByType.group": "会话重置（群组）",
  "session.resetByType.thread": "会话重置（线程）",
  "session.resetByChannel": "按通道重置会话",
  "session.store": "会话存储路径",
  "session.typingIntervalSeconds": "会话输入间隔（秒）",
  "session.typingMode": "会话输入模式",
  "session.parentForkMaxTokens": "会话父分支最大令牌数",
  "session.mainKey": "会话主键",
  "session.sendPolicy": "会话发送策略",
  "session.sendPolicy.default": "会话发送策略默认操作",
  "session.sendPolicy.rules": "会话发送策略规则",
  "session.sendPolicy.rules[].action": "会话发送规则操作",
  "session.sendPolicy.rules[].match": "会话发送规则匹配",
  "session.sendPolicy.rules[].match.channel": "会话发送规则通道",
  "session.sendPolicy.rules[].match.chatType": "会话发送规则聊天类型",
  "session.sendPolicy.rules[].match.keyPrefix": "会话发送规则键前缀",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "会话发送规则原始键前缀",
  "session.agentToAgent": "会话代理间",
  "session.agentToAgent.maxPingPongTurns": "代理间乒乓轮次",
  "session.threadBindings": "会话线程绑定",
  "session.threadBindings.enabled": "启用线程绑定",
  "session.threadBindings.idleHours": "线程绑定空闲超时（小时）",
  "session.threadBindings.maxAgeHours": "线程绑定最大存活时间（小时）",
  "session.maintenance": "会话维护",
  "session.maintenance.mode": "会话维护模式",
  "session.maintenance.pruneAfter": "会话修剪时间",
  "session.maintenance.pruneDays": "会话修剪天数（已弃用）",
  "session.maintenance.maxEntries": "会话最大条目数",
  "session.maintenance.rotateBytes": "会话轮转大小",
  "session.maintenance.resetArchiveRetention": "会话重置归档保留",
  "session.maintenance.maxDiskBytes": "会话最大磁盘预算",
  "session.maintenance.highWaterBytes": "会话磁盘高水位目标",
  cron: "定时任务",
  "cron.enabled": "启用定时任务",
  "cron.store": "定时任务存储路径",
  "cron.maxConcurrentRuns": "定时任务最大并发运行",
  "cron.retry": "定时任务重试策略",
  "cron.retry.maxAttempts": "定时任务最大重试次数",
  "cron.retry.backoffMs": "定时任务重试退避（毫秒）",
  "cron.retry.retryOn": "定时任务重试错误类型",
  "cron.webhook": "定时任务旧版 Webhook（已弃用）",
  "cron.webhookToken": "定时任务 Webhook Bearer 令牌",
  "cron.sessionRetention": "定时任务会话保留",
  "cron.runLog": "定时任务运行日志修剪",
  "cron.runLog.maxBytes": "定时任务运行日志最大字节数",
  "cron.runLog.keepLines": "定时任务运行日志保留行数",
  hooks: "钩子",
  "hooks.enabled": "启用钩子",
  "hooks.path": "钩子端点路径",
  "hooks.token": "钩子认证令牌",
  "hooks.defaultSessionKey": "钩子默认会话键",
  "hooks.allowRequestSessionKey": "钩子允许请求会话键",
  "hooks.allowedSessionKeyPrefixes": "钩子允许的会话键前缀",
  "hooks.allowedAgentIds": "钩子允许的代理 ID",
  "hooks.maxBodyBytes": "钩子最大请求体字节数",
  "hooks.presets": "钩子预设",
  "hooks.transformsDir": "钩子转换目录",
  "hooks.mappings": "钩子映射",
  "hooks.mappings[].id": "钩子映射 ID",
  "hooks.mappings[].match": "钩子映射匹配",
  "hooks.mappings[].match.path": "钩子映射匹配路径",
  "hooks.mappings[].match.source": "钩子映射匹配来源",
  "hooks.mappings[].action": "钩子映射操作",
  "hooks.mappings[].wakeMode": "钩子映射唤醒模式",
  "hooks.mappings[].name": "钩子映射名称",
  "hooks.mappings[].agentId": "钩子映射代理 ID",
  "hooks.mappings[].sessionKey": "钩子映射会话键",
  "hooks.mappings[].messageTemplate": "钩子映射消息模板",
  "hooks.mappings[].textTemplate": "钩子映射文本模板",
  "hooks.mappings[].deliver": "钩子映射投递回复",
  "hooks.mappings[].allowUnsafeExternalContent": "钩子映射允许不安全外部内容",
  "hooks.mappings[].channel": "钩子映射投递通道",
  "hooks.mappings[].to": "钩子映射投递目标",
  "hooks.mappings[].model": "钩子映射模型覆盖",
  "hooks.mappings[].thinking": "钩子映射思考覆盖",
  "hooks.mappings[].timeoutSeconds": "钩子映射超时（秒）",
  "hooks.mappings[].transform": "钩子映射转换",
  "hooks.mappings[].transform.module": "钩子转换模块",
  "hooks.mappings[].transform.export": "钩子转换导出",
  "hooks.gmail": "Gmail 钩子",
  "hooks.gmail.account": "Gmail 钩子账户",
  "hooks.gmail.label": "Gmail 钩子标签",
  "hooks.gmail.topic": "Gmail 钩子发布/订阅主题",
  "hooks.gmail.subscription": "Gmail 钩子订阅",
  "hooks.gmail.pushToken": "Gmail 钩子推送令牌",
  "hooks.gmail.hookUrl": "Gmail 钩子回调 URL",
  "hooks.gmail.includeBody": "Gmail 钩子包含正文",
  "hooks.gmail.maxBytes": "Gmail 钩子最大正文字节数",
  "hooks.gmail.renewEveryMinutes": "Gmail 钩子续订间隔（分钟）",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail 钩子允许不安全外部内容",
  "hooks.gmail.serve": "Gmail 钩子本地服务器",
  "hooks.gmail.serve.bind": "Gmail 钩子服务器绑定地址",
  "hooks.gmail.serve.port": "Gmail 钩子服务器端口",
  "hooks.gmail.serve.path": "Gmail 钩子服务器路径",
  "hooks.gmail.tailscale": "Gmail 钩子 Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail 钩子 Tailscale 模式",
  "hooks.gmail.tailscale.path": "Gmail 钩子 Tailscale 路径",
  "hooks.gmail.tailscale.target": "Gmail 钩子 Tailscale 目标",
  "hooks.gmail.model": "Gmail 钩子模型覆盖",
  "hooks.gmail.thinking": "Gmail 钩子思考覆盖",
  "hooks.internal": "内部钩子",
  "hooks.internal.enabled": "启用内部钩子",
  "hooks.internal.handlers": "内部钩子处理器",
  "hooks.internal.handlers[].event": "内部钩子事件",
  "hooks.internal.handlers[].module": "内部钩子模块",
  "hooks.internal.handlers[].export": "内部钩子导出",
  "hooks.internal.entries": "内部钩子条目",
  "hooks.internal.load": "内部钩子加载器",
  "hooks.internal.load.extraDirs": "内部钩子额外目录",
  "hooks.internal.installs": "内部钩子安装记录",
  web: "Web 通道",
  "web.enabled": "启用 Web 通道",
  "web.heartbeatSeconds": "Web 通道心跳间隔（秒）",
  "web.reconnect": "Web 通道重连策略",
  "web.reconnect.initialMs": "Web 重连初始延迟（毫秒）",
  "web.reconnect.maxMs": "Web 重连最大延迟（毫秒）",
  "web.reconnect.factor": "Web 重连退避因子",
  "web.reconnect.jitter": "Web 重连抖动",
  "web.reconnect.maxAttempts": "Web 重连最大尝试次数",
  discovery: "发现",
  "discovery.wideArea": "广域发现",
  "discovery.wideArea.enabled": "启用广域发现",
  "discovery.mdns": "mDNS 发现",
  canvasHost: "画布主机",
  "canvasHost.enabled": "启用画布主机",
  "canvasHost.root": "画布主机根目录",
  "canvasHost.port": "画布主机端口",
  "canvasHost.liveReload": "画布主机实时重载",
  talk: "语音",
  "talk.voiceId": "语音 ID",
  "talk.voiceAliases": "语音别名",
  "talk.modelId": "语音模型 ID",
  "talk.outputFormat": "语音输出格式",
  "talk.interruptOnSpeech": "语音打断",
  "talk.silenceTimeoutMs": "语音静默超时（毫秒）",
  messages: "消息",
  "messages.messagePrefix": "入站消息前缀",
  "messages.responsePrefix": "出站响应前缀",
  "messages.groupChat": "群聊规则",
  "messages.groupChat.mentionPatterns": "群组提及模式",
  "messages.groupChat.historyLimit": "群组历史限制",
  "messages.queue": "入站队列",
  "messages.queue.mode": "队列模式",
  "messages.queue.byChannel": "按通道队列模式",
  "messages.queue.debounceMs": "队列防抖（毫秒）",
  "messages.queue.debounceMsByChannel": "按通道队列防抖（毫秒）",
  "messages.queue.cap": "队列容量",
  "messages.queue.drop": "队列丢弃策略",
  "messages.inbound": "入站防抖",
  "messages.suppressToolErrors": "抑制工具错误警告",
  "messages.ackReaction": "确认反应表情",
  "messages.ackReactionScope": "确认反应范围",
  "messages.removeAckAfterReply": "回复后移除确认反应",
  "messages.statusReactions": "状态反应",
  "messages.statusReactions.enabled": "启用状态反应",
  "messages.statusReactions.emojis": "状态反应表情",
  "messages.statusReactions.timing": "状态反应时机",
  "messages.inbound.debounceMs": "入站消息防抖（毫秒）",
  "messages.inbound.byChannel": "按通道入站防抖（毫秒）",
  "messages.tts": "消息文字转语音",
  "talk.provider": "语音活跃提供者",
  "talk.providers": "语音提供者设置",
  "talk.providers.*.voiceId": "语音提供者语音 ID",
  "talk.providers.*.voiceAliases": "语音提供者语音别名",
  "talk.providers.*.modelId": "语音提供者模型 ID",
  "talk.providers.*.outputFormat": "语音提供者输出格式",
  "talk.providers.*.apiKey": "语音提供者 API 密钥", // pragma: allowlist secret
  "talk.apiKey": "语音 API 密钥", // pragma: allowlist secret
  channels: "通道",
  "channels.defaults": "通道默认值",
  "channels.defaults.groupPolicy": "默认群组策略",
  "channels.defaults.heartbeat": "默认心跳可见性",
  "channels.defaults.heartbeat.showOk": "心跳显示正常",
  "channels.defaults.heartbeat.showAlerts": "心跳显示警报",
  "channels.defaults.heartbeat.useIndicator": "心跳使用指示器",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram 自定义命令",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  "channels.modelByChannel": "通道模型覆盖",
  ...IRC_FIELD_LABELS,
  "channels.telegram.botToken": "Telegram Bot 令牌",
  "channels.telegram.dmPolicy": "Telegram 私信策略",
  "channels.telegram.configWrites": "Telegram 配置写入",
  "channels.telegram.commands.native": "Telegram 原生命令",
  "channels.telegram.commands.nativeSkills": "Telegram 原生技能命令",
  "channels.telegram.streaming": "Telegram 流式模式",
  "channels.telegram.retry.attempts": "Telegram 重试次数",
  "channels.telegram.retry.minDelayMs": "Telegram 重试最小延迟（毫秒）",
  "channels.telegram.retry.maxDelayMs": "Telegram 重试最大延迟（毫秒）",
  "channels.telegram.retry.jitter": "Telegram 重试抖动",
  "channels.telegram.network.autoSelectFamily": "Telegram 自动选择地址族",
  "channels.telegram.timeoutSeconds": "Telegram API 超时（秒）",
  "channels.telegram.capabilities.inlineButtons": "Telegram 内联按钮",
  "channels.telegram.execApprovals": "Telegram 执行审批",
  "channels.telegram.execApprovals.enabled": "启用 Telegram 执行审批",
  "channels.telegram.execApprovals.approvers": "Telegram 执行审批者",
  "channels.telegram.execApprovals.agentFilter": "Telegram 执行审批代理过滤器",
  "channels.telegram.execApprovals.sessionFilter": "Telegram 执行审批会话过滤器",
  "channels.telegram.execApprovals.target": "Telegram 执行审批目标",
  "channels.telegram.threadBindings.enabled": "启用 Telegram 线程绑定",
  "channels.telegram.threadBindings.idleHours": "Telegram 线程绑定空闲超时（小时）",
  "channels.telegram.threadBindings.maxAgeHours": "Telegram 线程绑定最大存活时间（小时）",
  "channels.telegram.threadBindings.spawnSubagentSessions": "Telegram 线程绑定子代理生成",
  "channels.telegram.threadBindings.spawnAcpSessions": "Telegram 线程绑定 ACP 生成",
  "channels.whatsapp.dmPolicy": "WhatsApp 私信策略",
  "channels.whatsapp.selfChatMode": "WhatsApp 自我电话模式",
  "channels.whatsapp.debounceMs": "WhatsApp 消息防抖（毫秒）",
  "channels.whatsapp.configWrites": "WhatsApp 配置写入",
  "channels.signal.dmPolicy": "Signal 私信策略",
  "channels.signal.configWrites": "Signal 配置写入",
  "channels.imessage.dmPolicy": "iMessage 私信策略",
  "channels.imessage.configWrites": "iMessage 配置写入",
  "channels.bluebubbles.dmPolicy": "BlueBubbles 私信策略",
  "channels.msteams.configWrites": "MS Teams 配置写入",
  "channels.irc.configWrites": "IRC 配置写入",
  "channels.discord.dmPolicy": "Discord 私信策略",
  "channels.discord.dm.policy": "Discord 私信策略",
  "channels.discord.configWrites": "Discord 配置写入",
  "channels.discord.proxy": "Discord 代理 URL",
  "channels.discord.commands.native": "Discord 原生命令",
  "channels.discord.commands.nativeSkills": "Discord 原生技能命令",
  "channels.discord.streaming": "Discord 流式模式",
  "channels.discord.streamMode": "Discord 流式模式（旧版）",
  "channels.discord.draftChunk.minChars": "Discord 草稿分块最小字符数",
  "channels.discord.draftChunk.maxChars": "Discord 草稿分块最大字符数",
  "channels.discord.draftChunk.breakPreference": "Discord 草稿分块换行偏好",
  "channels.discord.retry.attempts": "Discord 重试次数",
  "channels.discord.retry.minDelayMs": "Discord 重试最小延迟（毫秒）",
  "channels.discord.retry.maxDelayMs": "Discord 重试最大延迟（毫秒）",
  "channels.discord.retry.jitter": "Discord 重试抖动",
  "channels.discord.maxLinesPerMessage": "Discord 每条消息最大行数",
  "channels.discord.inboundWorker.runTimeoutMs": "Discord 入站工作线程超时（毫秒）",
  "channels.discord.eventQueue.listenerTimeout": "Discord 事件队列监听超时（毫秒）",
  "channels.discord.eventQueue.maxQueueSize": "Discord 事件队列最大大小",
  "channels.discord.eventQueue.maxConcurrency": "Discord 事件队列最大并发",
  "channels.discord.threadBindings.enabled": "启用 Discord 线程绑定",
  "channels.discord.threadBindings.idleHours": "Discord 线程绑定空闲超时（小时）",
  "channels.discord.threadBindings.maxAgeHours": "Discord 线程绑定最大存活时间（小时）",
  "channels.discord.threadBindings.spawnSubagentSessions": "Discord 线程绑定子代理生成",
  "channels.discord.threadBindings.spawnAcpSessions": "Discord 线程绑定 ACP 生成",
  "channels.discord.ui.components.accentColor": "Discord 组件主题色",
  "channels.discord.intents.presence": "Discord 在线状态意图",
  "channels.discord.intents.guildMembers": "Discord 服务器成员意图",
  "channels.discord.voice.enabled": "启用 Discord 语音",
  "channels.discord.voice.autoJoin": "Discord 语音自动加入",
  "channels.discord.voice.daveEncryption": "Discord 语音 DAVE 加密",
  "channels.discord.voice.decryptionFailureTolerance": "Discord 语音解密失败容忍度",
  "channels.discord.voice.tts": "Discord 语音文字转语音",
  "channels.discord.pluralkit.enabled": "启用 Discord PluralKit",
  "channels.discord.pluralkit.token": "Discord PluralKit 令牌",
  "channels.discord.activity": "Discord 在线状态活动",
  "channels.discord.status": "Discord 在线状态",
  "channels.discord.autoPresence.enabled": "启用 Discord 自动在线状态",
  "channels.discord.autoPresence.intervalMs": "Discord 自动在线状态检查间隔（毫秒）",
  "channels.discord.autoPresence.minUpdateIntervalMs":
    "Discord 自动在线状态最小更新间隔（毫秒）",
  "channels.discord.autoPresence.healthyText": "Discord 自动在线状态健康文本",
  "channels.discord.autoPresence.degradedText": "Discord 自动在线状态降级文本",
  "channels.discord.autoPresence.exhaustedText": "Discord 自动在线状态耗尽文本",
  "channels.discord.activityType": "Discord 在线状态活动类型",
  "channels.discord.activityUrl": "Discord 在线状态活动 URL",
  "channels.slack.dm.policy": "Slack 私信策略",
  "channels.slack.dmPolicy": "Slack 私信策略",
  "channels.slack.configWrites": "Slack 配置写入",
  "channels.slack.commands.native": "Slack 原生命令",
  "channels.slack.commands.nativeSkills": "Slack 原生技能命令",
  "channels.slack.allowBots": "Slack 允许机器人消息",
  "channels.discord.allowBots": "Discord 允许机器人消息",
  "channels.discord.token": "Discord Bot 令牌",
  "channels.slack.botToken": "Slack Bot 令牌",
  "channels.slack.appToken": "Slack App 令牌",
  "channels.slack.userToken": "Slack 用户令牌",
  "channels.slack.userTokenReadOnly": "Slack 用户只读令牌",
  "channels.slack.streaming": "Slack 流式模式",
  "channels.slack.nativeStreaming": "Slack 原生流式",
  "channels.slack.streamMode": "Slack 流式模式（旧版）",
  "channels.slack.thread.historyScope": "Slack 线程历史范围",
  "channels.slack.thread.inheritParent": "Slack 线程父级继承",
  "channels.slack.thread.initialHistoryLimit": "Slack 线程初始历史限制",
  "channels.mattermost.botToken": "Mattermost Bot 令牌",
  "channels.mattermost.baseUrl": "Mattermost 基础 URL",
  "channels.mattermost.configWrites": "Mattermost 配置写入",
  "channels.mattermost.chatmode": "Mattermost 聊天模式",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar 前缀",
  "channels.mattermost.requireMention": "Mattermost 需要提及",
  "channels.signal.account": "Signal 账户",
  "channels.imessage.cliPath": "iMessage CLI 路径",
  "agents.list[].skills": "代理技能筛选",
  "agents.list[].identity.avatar": "代理头像",
  "agents.list[].heartbeat.suppressToolErrorWarnings":
    "代理心跳抑制工具错误警告",
  "agents.list[].sandbox.browser.network": "代理沙箱浏览器网络",
  "agents.list[].sandbox.browser.cdpSourceRange": "代理沙箱浏览器 CDP 源端口范围",
  "agents.list[].sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "代理沙箱 Docker 允许容器命名空间加入",
  "discovery.mdns.mode": "mDNS 发现模式",
  plugins: "插件",
  "plugins.enabled": "启用插件",
  "plugins.allow": "插件允许列表",
  "plugins.deny": "插件拒绝列表",
  "plugins.load": "插件加载器",
  "plugins.load.paths": "插件加载路径",
  "plugins.slots": "插件槽位",
  "plugins.slots.memory": "记忆插件",
  "plugins.slots.contextEngine": "上下文引擎插件",
  "plugins.entries": "插件条目",
  "plugins.entries.*.enabled": "启用插件",
  "plugins.entries.*.hooks": "插件钩子策略",
  "plugins.entries.*.hooks.allowPromptInjection": "允许提示注入钩子",
  "plugins.entries.*.apiKey": "插件 API 密钥", // pragma: allowlist secret
  "plugins.entries.*.env": "插件环境变量",
  "plugins.entries.*.config": "插件配置",
  "plugins.installs": "插件安装记录",
  "plugins.installs.*.source": "插件安装来源",
  "plugins.installs.*.spec": "插件安装规范",
  "plugins.installs.*.sourcePath": "插件安装来源路径",
  "plugins.installs.*.installPath": "插件安装路径",
  "plugins.installs.*.version": "插件安装版本",
  "plugins.installs.*.resolvedName": "插件解析包名",
  "plugins.installs.*.resolvedVersion": "插件解析包版本",
  "plugins.installs.*.resolvedSpec": "插件解析包规范",
  "plugins.installs.*.integrity": "插件解析完整性",
  "plugins.installs.*.shasum": "插件解析校验和",
  "plugins.installs.*.resolvedAt": "插件解析时间",
  "plugins.installs.*.installedAt": "插件安装时间",
};
